### ISSUE TITLE
Will Colab trained models work with this repo?

### ISSUE THREAD

**Issue by marcivanmanalac** [roboflow/homepage-demo#1]
I trained a YOLOv8 object-detection model using the Google Colab tutorial and received the .PT files as output. I've been reading the [web browser inference guide](https://docs.roboflow.com/inference/web-browser) and saw some mentions about using Roboflow's trained models in order to use `roboflow.load(options)` . Would this work using my downloaded .PT model locally or would I need to train on Roboflow to use this? How would I go about using a local model if so?

**Comment by Jacobsolawetz** [comment]
@marcivanmanalac certainly! Be sure to [upload your YOLOv8 weights](https://docs.roboflow.com/upload-weights#yolov5-and-yolov8) after training

YOLOv8 object detection is currently supported for web browser inference

**Comment by MadeWithStone** [comment]
Yes this is supported functionality if you upload your model to roboflow and it is supported by inferencejs. https://www.npmjs.com/package/inferencejs
