### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by pahotari** [roboflow/homepage-demo#3]
Hello,

When I activate the webcam and use this demo for an extended period, it consumes all available GPU memory. Upon checking the console, I noticed a warning: "index.ts:175 High memory usage in GPU: 1173.86 MB, most likely due to a memory leak." I suspect that there might be an issue in roboflow.js.

I'm interested in creating a solution that functions well in a web browser, and roboflow.js seems like a good choice. However, the current memory leak issue prevents me from using it effectively. I'm curious if there are any plans to address and correct this memory leak in roboflow.js.

**Comment by MadeWithStone** [comment]
@pahotari We've released a new library called inferencejs which resolves the memory leak and is now implemented in the latest version of this repo. https://www.npmjs.com/package/inferencejs

**Comment by MadeWithStone** [comment]
closing as the issue has been resolved
